"""fix_tc_pf_to_string

Revision ID: 14d9dcf15135
Revises: 
Create Date: 2026-02-18 18:33:40.886752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d9dcf15135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('tc',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('pf',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('pf',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('tc',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
