"""categorie_date_creation

Revision ID: 33728e02f966
Revises: a4c6a998295b
Create Date: 2026-02-18 19:06:46.119022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33728e02f966'
down_revision = 'a4c6a998295b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('date_creation')

    # ### end Alembic commands ###
