"""first_migrate

Revision ID: 4a5e8f3cb9b5
Revises: 8fc110b494a7
Create Date: 2026-02-19 18:40:14.046889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5e8f3cb9b5'
down_revision = '8fc110b494a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.DateTime(), nullable=True))

    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_actuel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_minimum', sa.Integer(), nullable=True))
        batch_op.alter_column('tc',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('pf',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('pf',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('tc',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('stock_minimum')
        batch_op.drop_column('stock_actuel')

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.drop_column('date_creation')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('nom',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
