"""tf_pf_change_type

Revision ID: 6cb65289bf79
Revises: 4a5e8f3cb9b5
Create Date: 2026-02-20 11:15:09.039670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb65289bf79'
down_revision = '4a5e8f3cb9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('tc',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('pf',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('pf',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('tc',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
