"""unite_date_creation

Revision ID: 8fc110b494a7
Revises: 33728e02f966
Create Date: 2026-02-18 19:10:25.708612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc110b494a7'
down_revision = '33728e02f966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unites_mesure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unites_mesure', schema=None) as batch_op:
        batch_op.drop_column('date_creation')

    # ### end Alembic commands ###
