"""fix_tc_pf_to_string

Revision ID: a4c6a998295b
Revises: 14d9dcf15135
Create Date: 2026-02-18 18:59:23.200420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c6a998295b'
down_revision = '14d9dcf15135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('date_creation')

    with op.batch_alter_table('unites_mesure', schema=None) as batch_op:
        batch_op.drop_column('date_creation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unites_mesure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.DATETIME(), nullable=True))
        batch_op.alter_column('nom',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
