"""tf_pf_change_type_artstockable

Revision ID: dca0055b9a35
Revises: 6cb65289bf79
Create Date: 2026-02-20 11:20:09.196947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca0055b9a35'
down_revision = '6cb65289bf79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('tc',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('pf',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('article_stockable',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=5),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.alter_column('article_stockable',
               existing_type=sa.String(length=5),
               type_=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('pf',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('tc',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
